### ISSUE TITLE
Obtaining the IMAP directory separator character

### ISSUE THREAD

**Issue by benr77** [tedious/Fetch#101]
Is there any way to get the IMAP directory separator character? Usually it can be '.' or '/' but it varies from mailserver to mailserver. 

I am writing an app that needs to create mailboxes on a variety of different mailservers so I need to programmatically extract this separator character so I can correctly construct the path to the new mailbox etc.

**Comment by tedivm** [comment]
Closing this out as I've merged the pull request.
