### ISSUE TITLE
imap_rfc822_parse_headers is not supported by HHVM

### ISSUE THREAD

**Issue by martinssipenko** [tedious/Fetch#103]
Function `imap_rfc822_parse_headers` usedn in https://github.com/tedious/Fetch/blob/master/src/Fetch/Message.php#L299 is not supported by HHVM.

http://docs.hhvm.com/manual/en/function.imap-rfc822-parse-headers.php

I'd be happy to submit a Pull Requests as long as you think it would make sense to change this to something else.

**Comment by tomsommer** [comment]
The imap_rfc822_parse_headers() function is broken anyway, as it ignores custom headers.

Run $message->getRawheaders() and parse the headers with a regexp instead.

Like:

```
preg_match_all('/([^: ]+): (.+?(?:\r\n\s(?:.+?))*)\r\n/m', $headers, $matches)
$headers = array_combine($matches[1], $matches[2]);
```

**Comment by tedivm** [comment]
You want to make a pull request? You'll get all sorts of points if you get this working on HHVM.

**Comment by tomsommer** [comment]
It would break compat as it would return an array instead of an object, but we could typecast it to (object) I guess
