### ISSUE TITLE
Unsupported encoding in mb_convert_encoding results in fatal error

### ISSUE THREAD

**Issue by AaronVanGeffen** [tedious/Fetch#107]
Per 38dd385cb8d07e5a4caa7a5e8b6fb3de2fbc7f13, calls to mb_convert_encoding are encapsulated in try…catch statements, however, `mb_convert_encoding` does not appear to yield exceptions — instead, unsupported character sets result in a fatal error:
```
2: mb_convert_encoding(): Illegal character encoding specified
```

A solution to this would be to check what conversions *are* supported with [`mb_list_encodings`](http://php.net/manual/en/function.mb-list-encodings.php), but I'll leave that up to you to decide, seeing as you may want to do away with the apparently unnecessary try…catch statement, too.

On a sidenote, the issue I was having had to do with mails being encoded with 'unicode-1-1-utf-7', which is [not supported by mbstring](http://php.net/manual/en/mbstring.supported-encodings.php). I worked around it using the following ugly hack:

```
diff a/Fetch/Message.php b/Fetch/Message.php
--- a/Fetch/Message.php
+++ b/Fetch/Message.php
@@ -479,7 +479,7 @@ class Message
 
             if (!empty($parameters['charset']) && $parameters['charset'] !== self::$charset) {
                 $mb_converted = false;
-                if (function_exists('mb_convert_encoding')) {
+                if (function_exists('mb_convert_encoding') && $parameters['charset'] != 'unicode-1-1-utf-7') {
                     try {
                         $messageBody = mb_convert_encoding($messageBody, self::$charset, $parameters['charset']);
                         $mb_converted = true;
```

**Comment by tedivm** [comment]
This should be resolved by the PR I just merged.
