### ISSUE TITLE
imap_fetchbody marks all my mails in a mailbox as "read" whereas they should remain "unread"

### ISSUE THREAD

**Issue by Symphlion** [tedious/Fetch#120]
It seems that:

imap_fetchbody($this->imapStream, $this->uid, $partIdentifier, FT_UID)

This particular line of code is stored in Message.php around 470.
This particular line of code is marking all the mails in my mailbox as read. I cannot figure out why this happens. I wish I had a solution, but I can`t find out what the reason for this behaviour is. 

In any case, I tested using Roundcube on one tab, my code on the second. I`m marking them as unread in Roundcube, make sure they are marked as unread, then run the code and eventually reached this line of code. If I comment out this line of code, none of my mails are changed and remain unread ( which is what should be the case ). 

I don`t have any code to quickly reproduce this problem, but I figure i`m not alone in this?

**Comment by Symphlion** [comment]
Oh it seems there`s a flag you can append, maybe can you change the FT_UID flag and append FT_SEEK? It prevents the mail from being marked as read.

**Comment by Prestaspirit** [comment]
https://github.com/tedious/Fetch/pull/136

**Comment by tedivm** [comment]
I'ved merged in #136.

**Comment by charlieWasp** [comment]
Is it so for POP3 servers?
