### ISSUE TITLE
Please add a new Tag

### ISSUE THREAD

**Issue by VasuLief** [tedious/Fetch#127]
Since there are 18 commits after the last tag, can you please add a new tag like 0.6.2?

Thanks!

**Comment by benr77** [comment]
+1

**Comment by tedivm** [comment]
I just merged a bunch of pull requests and asked a few people to rebase ones that are outdated. I'll get a tag in the new week or so.

**Comment by tomsommer** [comment]
Please merge some more and tag :)

**Comment by benr77** [comment]
Yes, it's been 6 months since the last tagged release. +1 for a new tag it's been a month since you agreed! 

Thanks!

**Comment by tedivm** [comment]
Done! I went through and pulled some more merge requests and did some cleanups as well.

If anyone wants to go through and either rebase or redo the conflicted merge questions I'll take a stab at merging those in as well.
