### ISSUE TITLE
 iconv(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by huglester** [tedious/Fetch#13]
Hello, on some messages I get this notice:

ErrorException [ Notice ]: iconv(): Detected an illegal character in input string
APPPATH/vendor/tedivm/fetch/src/Fetch/Message.php @ line 421:

I debuged thesemessages, I see that the values during error are:
$parameters['charset'] = utf-8;
self::$charset = UTF-8//TRANSLIT;

Any idea on how to fix it?

**Comment by tedivm** [comment]
Character encoding has been updated with the current release. I'm asking that people submit new tickets for any bugs that they find.
