### ISSUE TITLE
SSL/TLS handshake with the IMAP server

### ISSUE THREAD

**Issue by skynet** [tedious/Fetch#140]
It looks like SSL/TLS handshake is handled at a different (PHP) layer. Are there methods for adjusting these options, built into this library? I can see some options here https://github.com/tedious/Fetch/blob/master/src/Fetch/Server.php :
```
    /**
     * These are the flags that depend on ssl support being compiled into imap.
     *
     * @var array
     */
    public static $sslFlags = array('ssl', 'validate-cert', 'novalidate-cert', 'tls', 'notls');
    /**
     * This is used to prevent the class from putting up conflicting tags. Both directions- key to value, value to key-
     * are checked, so if "novalidate-cert" is passed then "validate-cert" is removed, and vice-versa.
     *
     * @var array
     */
    public static $exclusiveFlags = array('validate-cert' => 'novalidate-cert', 'tls' => 'notls');
```

Do you have a practical example on how to use different certs for a particular IMAP service, or do we have to use same valid root certificate that comes installed on a machine, in my case Linux machine?

Thanks.

**Comment by tedivm** [comment]
This library doesn't deal with certificates directly- you need to install the needed certs on your system.

**Comment by skynet** [comment]
Makes sense, thank you.
