### ISSUE TITLE
windows-1255 encoding fails

### ISSUE THREAD

**Issue by tomsommer** [tedious/Fetch#141]
Messages with windows-1255 encoding trigger an error:

Warning: mb_convert_encoding(): Illegal character encoding specified in ... /vendor/tedivm/fetch/src/Fetch/Message.php on line 485

**Comment by tedivm** [comment]
Without the source email this will be difficult to resolve.

**Comment by DarkAllMan** [comment]
I think the solution is:
http://www.php.net/manual/en/function.imap-utf8.php#102081

So it needs to be added to the decoding of the subject and addresses decoding

**Comment by tomsommer** [comment]
Maybe #115 might help

**Comment by tedivm** [comment]
Character encoding has been updated with the current release. I'm asking that people submit new tickets for any bugs that they find.
