### ISSUE TITLE
Style tag affecting body style

### ISSUE THREAD

**Issue by carusogabriel** [tedious/Fetch#155]
How can I remove the style tag of an email?
Why? The style tag style meu body tag, so with an Email comes with body color: red, my whole page, including other email get an red text!

**Comment by bjornpost** [comment]
* Escape the output with `htmlspecialchars()` or a template library like Twig
* Strip all HTML with `strip_tags()`
* Strip all HTML tags with a couple of exceptions `strip_tags($emailBody, [ 'b', 'ul', 'li', .. ])`

This isn't something Fetch will/should solve for you.

**Comment by tedivm** [comment]
Agreed with @bjornpost - if this project tried to deal with all encoding issues I'd not only lose my mind, but so would all of the developers using this library who then had to deal with a variety of encoding issues as a result.
