### ISSUE TITLE
Open Shared Inbox

### ISSUE THREAD

**Issue by vajiralasantha** [tedious/Fetch#224]
I'm using this lib for years now and recently came to a situation where I have to read some shared office365 inboxes. Is that possible with this lib? If so what is the procedure of doing that.

Thanks

**Comment by tedivm** [comment]
This is more of a microsoft issue, but it seems that they do allow access over IMAP for shared mailboxes. I found [this article](https://adam-hand.com/2017/07/25/connect-a-shared-mailbox-from-o365-to-outlook-via-imap/) with details.

**Comment by vajiralasantha** [comment]
> This is more of a microsoft issue, but it seems that they do allow access over IMAP for shared mailboxes. I found [this article](https://adam-hand.com/2017/07/25/connect-a-shared-mailbox-from-o365-to-outlook-via-imap/) with details.

Thanks I will give them a try and update.
