### ISSUE TITLE
Question about versioning on the Packagist.

### ISSUE THREAD

**Issue by gabrielcaixeta** [tedious/Fetch#230]
Hi @tedivm,

I update my application to be compatible with PHP 7.4, using version 0.7.1 of this package by the composer.
Meanwhile, some strange behaviors are happening when getting the subject.

![image](https://user-images.githubusercontent.com/8334460/201359399-224ea88d-0cd2-456a-9270-523e6b3a8e52.png)

I saw the PR #147, which merged in the branch master, seems to fix the problem.
![image](https://user-images.githubusercontent.com/8334460/201359440-e038c279-7035-4276-bdf8-03b3fe0ca495.png)

 So, I have to update my composer.json to use dev-master. After some tests, the email's subject was decoded correctly.

![image](https://user-images.githubusercontent.com/8334460/201359653-d46ab499-9809-4e8c-bf16-a22bc789157a.png)

That way, my question is if possible to put this solution on a v0.7.2 on the  Packigst. Since use dev-master I think to be not a good practice to do.

**Comment by tedivm** [comment]
I've published v0.7.2.

**Comment by gabrielcaixeta** [comment]
> I've published v0.7.2.

Thank you very much, @tedivm.
