### ISSUE TITLE
attachment - only from the email body

### ISSUE THREAD

**Issue by Magnificent-Big-J** [tedious/Fetch#231]
I've just discovered that email attachments can be fetched, but those inserted using the server's attach functionality may not be retrievable. 

Do you have any suggestions on how we can retrieve all attachments, not just those embedded in the email body?

**Comment by tedivm** [comment]
There's really not much that can be done here, as this library is simply a wrapper over the PHP IMAP extension. As the IMAP standard evolves, and the extension itself doesn't, more of these issues will continue to crop up.
