### ISSUE TITLE
Proposal - Middleware

### ISSUE THREAD

**Issue by fideloper** [tedious/Fetch#35]
Hey! What would you think of adopting a "middleware" approach that would allow developers to add in middleware to messaging parsing.

For example, it would be nice to have a middleware which handled the UTF-8 encoding of the subject, html and plaintext email. Another middleware might be to attempt to clean HTML emails, which often come with a lot of useless cruft which makes displaying an html email in the browser difficult.

This helps in situations where more encoding or extra parsing is required by business logic. (You can likely wrap your business logic over/around this class, but the middleware approach makes for some interesting abilities).

Some middleware ("core middleware"?) could be created by extracting current functionalities such as encoding and other things which aren't strictly email related functionalities (potentially allowing you to clear that code out from being "hard coded" into the email classes).

Let me know what you think! (I can take constructive criticism :D )

**Comment by tedivm** [comment]
I'm closing this ticket out until a more solid proposal comes along.
