### ISSUE TITLE
option to specify FT_PEEK

### ISSUE THREAD

**Issue by leeoniya** [tedious/Fetch#54]
currently, fetching messages automatically marks them as read. this is not always desirable behavior and there's currently no way to change this.

it would be helpful to either add the option (FT_PEEK) flag to getMessages() or something similar.

i think it makes sense to actually have it on by default.

thanks!

**Comment by kdauzickas-nfq** [comment]
Is it possible to get this merged? This allows behavior which currently can't be achieved cleanly

**Comment by tedivm** [comment]
Unfortunately it'll have to be rebased before it can be merged. I may just port the changes in myself.

**Comment by tedivm** [comment]
If we can get this rebased I'll merge it in. I also have no issue making this the default option (in fact that would probably be preferred).

**Comment by tedivm** [comment]
This was resolved by PR #136.
