### ISSUE TITLE
imap_savebody issue on Windows

### ISSUE THREAD

**Issue by eleftrik** [tedious/Fetch#74]
Method \Fetch\Attachment\saveAs, this line (about 221, latest pull):

$result = imap_savebody($this->imapStream, $filePointer, $this->messageId, $this->partId ?: 1, FT_UID);

...on Windows (PHP 5.4.30 with XDebug, Apache 2.2.18) makes PHP crash. When the code reaches this line, the execution suddenly stops. No, errors, no lines in error.log, no HTTP status returned.

This is obviously not related to Fetch code, but I could bypass this problem by inserting a line like this (before the one with imap_savebody):

$temp = imap_fetchbody($this->imapStream, $this->messageId, $this->partId ?: 1, FT_UID);

Would it be possible to put something like this in the next pull?

Calling imap_fetchbody before imap_savebody seems to solve this strange issue. Here I read something about imap_fetchbody and Apache that crashes: http://www.tek-tips.com/viewthread.cfm?qid=1574115

Thank you for your attention.

**Comment by siriuscor** [comment]
yes, add imap_fetchbody before imap_savebody solve my problem

**Comment by eleftrik** [comment]
@siriuscor, I'm glad it worked!

**Comment by tedivm** [comment]
Someone want to make a pull request?

**Comment by eleftrik** [comment]
@tedivm, I'm sorry, I'm quite new to GIT, I use it only for local development. My apologies.

**Comment by orzilca** [comment]
@tedivm , I've created a pull request fixing the issue.
774cfb26482b25ba6e11017c1e86719ad22a3fdd

**Comment by tedivm** [comment]
Merge request pulled.
