### ISSUE TITLE
Undefined property: stdClass::$host

### ISSUE THREAD

**Issue by gpilla** [tedious/Fetch#95]
Undefined property: stdClass::$host

... /vendor/tedivm/fetch/src/Fetch/Message.php:573

It can be reproduced when the To header is not an email.

Example:
``
To: undisclosed-recipients:;
``

It happened when i received a email from a Redmine app.

I fast fixed adding this:

```php
$currentAddress['address'] = $address->mailbox . '@' . $address->host;
if (isset($address->personal))
    $currentAddress['name'] = $address->personal;
$outputAddresses[] = $currentAddress;
```

Changing with this...

```php
if (property_exists($address, 'mailbox') && $address->mailbox != 'undisclosed-recipients') {
     $currentAddress['address'] = $address->mailbox . '@' . $address->host;
     if (isset($address->personal))
        $currentAddress['name'] = $address->personal;
        $outputAddresses[] = $currentAddress;
}
```

I know that is a fast and quite dirty solution.

Sorry for my english.

**Comment by benr77** [comment]
+1 for this. Processing any inbox for mail will almost certainly encounter this scenario fairly regularly. 

I get the following notices

```
Notice: Undefined property: stdClass::$host in /home/chaletops/deployments/develop/releases/20150128181823/vendor/tedivm/fetch/src/Fetch/Message.php line 627
```

```
Notice: Undefined property: stdClass::$mailbox in /home/chaletops/deployments/develop/releases/20150128181823/vendor/tedivm/fetch/src/Fetch/Message.php line 627
```

**Comment by gpilla** [comment]
This should be closed, maybe there is better solutions, but is working now.
